[package]
name = "kiwi"
version = "0.1.0"
description = "ğŸ« Schoolwork as code"
authors = ["Matt Gleich <email@mattglei.ch>"]
edition = "2018"
repository = "https://github.com/gleich/kiwi/"
homepage = "https://github.com/gleich/kiwi/"
license = "MPL-2.0"
keywords = []

[dependencies]
clap = "2.33.3"
toml = "0.5.8"
serde = { version = "1.0.127", features = ["derive"] }
dialoguer = "0.8.0"
anyhow = "1.0.42"
colored = "2.0.0"
