[package]
name = "kiwi-cli"
version = "1.0.0"
description = "ğŸ« Schoolwork as code"
authors = ["Matt Gleich <email@mattglei.ch>"]
edition = "2021"
repository = "https://github.com/gleich/kiwi/"
homepage = "https://kiwi.docs.mattglei.ch"
license = "MPL-2.0"
keywords = ["kiwi", "cli", "latex", "markdown"]

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
strum = "0.23.0"
strum_macros = "0.23.0"
toml = "0.5.8"
anyhow = "1.0.53"
clap = "3.0.13"

[[bin]]
name = "kiwi"
path = "src/main.rs"
