[package]
name = "kiwi-cli"
version = "1.0.0"
description = "ğŸ« Schoolwork as code"
authors = ["Matt Gleich <email@mattglei.ch>"]
edition = "2021"
repository = "https://github.com/gleich/kiwi/"
homepage = "https://kiwi.docs.mattglei.ch"
license = "MPL-2.0"
keywords = ["kiwi", "cli", "latex", "markdown"]

[dependencies]

[[bin]]
name = "kiwi"
path = "src/main.rs"
