[package]
name = "kiwi"
version = "0.1.0"
description = "ğŸ« Schoolwork as code"
authors = ["Matt Gleich <email@mattglei.ch>"]
edition = "2018"
repository = "https://github.com/gleich/kiwi/"
homepage = "https://github.com/gleich/kiwi/"
license = "MPL-2.0"
keywords = []

[dependencies]
